# Generated by Django 4.2.26 on 2025-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_recurso', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.PositiveIntegerField()),
            ],
        ),
    ]
